### ISSUE TITLE
Issue in Transpiling TypeScript to Lua

### ISSUE THREAD

**Issue by TaBayram** [cipherxof/wc3-ts-template#12]
I followed through the setup guide right until "npm run test" which gave me errors:

```
node_modules/lua-types/core/coroutine.d.ts:31:8 - error TS2304: Cannot find name 'LuaMultiReturn'.

31     ): LuaMultiReturn<[true, ...any[]] | [false, string]>;
          ~~~~~~~~~~~~~~

node_modules/lua-types/core/coroutine.d.ts:50:68 - error TS2304: Cannot find name 'LuaMultiReturn'.

50     function wrap(f: (...args: any[]) => any): (...args: any[]) => LuaMultiReturn<any[]>;
                                                                      ~~~~~~~~~~~~~~

node_modules/lua-types/core/coroutine.d.ts:56:37 - error TS2304: Cannot find name 'LuaMultiReturn'.

56     function yield(...args: any[]): LuaMultiReturn<any[]>;
                                       ~~~~~~~~~~~~~~

node_modules/lua-types/core/global.d.ts:123:51 - error TS2304: Cannot find name 'LuaIterable'.

123 declare function ipairs<T>(t: Record<number, T>): LuaIterable<LuaMultiReturn<[number, T]>>;
                                                      ~~~~~~~~~~~

node_modules/lua-types/core/global.d.ts:123:63 - error TS2304: Cannot find name 'LuaMultiReturn'.

123 declare function ipairs<T>(t: Record<number, T>): LuaIterable<LuaMultiReturn<[number, T]>>;
                                                                  ~~~~~~~~~~~~~~

node_modules/lua-types/core/global.d.ts:142:52 - error TS2304: Cannot find name 'LuaMultiReturn'.

142 declare function next(table: object, index?: any): LuaMultiReturn<[any, any] | []>;
                                                       ~~~~~~~~~~~~~~

node_modules/lua-types/core/global.d.ts:156:34 - error TS2304: Cannot find name 'LuaIterable'.

156 declare function pairs<T>(t: T): LuaIterable<LuaMultiReturn<[keyof T, T[keyof T]]>>;
                                     ~~~~~~~~~~~

node_modules/lua-types/core/global.d.ts:156:46 - error TS2304: Cannot find name 'LuaMultiReturn'.

156 declare function pairs<T>(t: T): LuaIterable<LuaMultiReturn<[keyof T, T[keyof T]]>>;
                                                 ~~~~~~~~~~~~~~

node_modules/lua-types/core/global.d.ts:170:4 - error TS2304: Cannot find name 'LuaMultiReturn'.

170 ): LuaMultiReturn<[true, R] | [false, string]>;
       ~~~~~~~~~~~~~~

node_modules/lua-types/core/global.d.ts:175:4 - error TS2304: Cannot find name 'LuaMultiReturn'.

175 ): LuaMultiReturn<[true, R] | [false, string]>;
       ~~~~~~~~~~~~~~

node_modules/lua-types/core/global.d.ts:219:58 - error TS2304: Cannot find name 'LuaMultiReturn'.

219 declare function select<T>(index: number, ...args: T[]): LuaMultiReturn<T[]>;
                                                             ~~~~~~~~~~~~~~

node_modules/lua-types/core/math.d.ts:81:31 - error TS2304: Cannot find name 'LuaMultiReturn'.

81     function modf(x: number): LuaMultiReturn<[number, number]>;
                                 ~~~~~~~~~~~~~~

node_modules/lua-types/core/os.d.ts:111:40 - error TS2304: Cannot find name 'LuaMultiReturn'.

111     function remove(filename: string): LuaMultiReturn<[true] | [undefined, string]>;
                                           ~~~~~~~~~~~~~~

node_modules/lua-types/core/os.d.ts:118:56 - error TS2304: Cannot find name 'LuaMultiReturn'.

118     function rename(oldname: string, newname: string): LuaMultiReturn<[true] | [undefined, string]>;
                                                           ~~~~~~~~~~~~~~

node_modules/lua-types/core/string.d.ts:29:55 - error TS2304: Cannot find name 'LuaMultiReturn'.

29     function byte(s: string, i?: number, j?: number): LuaMultiReturn<number[]>;
                                                         ~~~~~~~~~~~~~~

node_modules/lua-types/core/string.d.ts:65:8 - error TS2304: Cannot find name 'LuaMultiReturn'.

65     ): LuaMultiReturn<[number, number, ...string[]] | []>;
          ~~~~~~~~~~~~~~

node_modules/lua-types/core/string.d.ts:124:50 - error TS2304: Cannot find name 'LuaIterable'.

124     function gmatch(s: string, pattern: string): LuaIterable<LuaMultiReturn<string[]>>;
                                                     ~~~~~~~~~~~

node_modules/lua-types/core/string.d.ts:124:62 - error TS2304: Cannot find name 'LuaMultiReturn'.

124     function gmatch(s: string, pattern: string): LuaIterable<LuaMultiReturn<string[]>>;
                                                                 ~~~~~~~~~~~~~~

node_modules/lua-types/core/string.d.ts:158:8 - error TS2304: Cannot find name 'LuaMultiReturn'.

158     ): LuaMultiReturn<[string, number]>;
           ~~~~~~~~~~~~~~

node_modules/lua-types/core/string.d.ts:180:64 - error TS2304: Cannot find name 'LuaMultiReturn'.

180     function match(s: string, pattern: string, init?: number): LuaMultiReturn<string[]>;
                                                                   ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus-or-jit.d.ts:39:4 - error TS2304: Cannot find name 'LuaMultiReturn'.

39 ): LuaMultiReturn<[() => any] | [undefined, string]>;
      ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus-or-jit.d.ts:49:4 - error TS2304: Cannot find name 'LuaMultiReturn'.

49 ): LuaMultiReturn<[() => any] | [undefined, string]>;
      ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus-or-jit.d.ts:60:4 - error TS2304: Cannot find name 'LuaMultiReturn'.

60 ): LuaMultiReturn<[true, R] | [false, E]>;
      ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus-or-jit.d.ts:66:4 - error TS2304: Cannot find name 'LuaMultiReturn'.

66 ): LuaMultiReturn<[true, R] | [false, E]>;
      ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus-or-jit.d.ts:94:61 - error TS2304: Cannot find name 'LuaMultiReturn'.

94     function getlocal(f: Function | number, local: number): LuaMultiReturn<[string, any]>;
                                                               ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus-or-jit.d.ts:99:8 - error TS2304: Cannot find name 'LuaMultiReturn'.

99     ): LuaMultiReturn<[string, any]>;
          ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus.d.ts:83:33 - error TS2304: Cannot find name 'LuaMultiReturn'.

83         | ((modname: string) => LuaMultiReturn<[(modname: string) => void]>)
                                   ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus.d.ts:84:36 - error TS2304: Cannot find name 'LuaMultiReturn'.

84         | (<T>(modname: string) => LuaMultiReturn<[(modname: string, extra: T) => T, T]>)
                                      ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus.d.ts:97:48 - error TS2304: Cannot find name 'LuaMultiReturn'.

97     function unpack<T extends any[]>(list: T): LuaMultiReturn<T[]>;
                                                  ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus.d.ts:98:59 - error TS2304: Cannot find name 'LuaMultiReturn'.

98     function unpack<T>(list: T[], i: number, j?: number): LuaMultiReturn<T[]>;
                                                             ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus.d.ts:139:8 - error TS2304: Cannot find name 'LuaMultiReturn'.

139     ): LuaMultiReturn<[true | undefined, 'exit' | 'signal', number]>;
           ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.2-plus.d.ts:167:25 - error TS2304: Cannot find name 'LuaMultiReturn'.

167     function running(): LuaMultiReturn<[LuaThread, boolean]>;
                            ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.3-plus.d.ts:92:60 - error TS2304: Cannot find name 'LuaMultiReturn'.

92     function unpack(fmt: string, s: string, pos?: number): LuaMultiReturn<any[]>;
                                                              ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.3-plus.d.ts:152:35 - error TS2304: Cannot find name 'LuaMultiReturn'.

152     ): [(s: S, index?: number) => LuaMultiReturn<[number, number]>, S, 0];
                                      ~~~~~~~~~~~~~~

node_modules/lua-types/special/5.3-plus.d.ts:159:60 - error TS2304: Cannot find name 'LuaMultiReturn'.

159     function codepoint(s: string, i?: number, j?: number): LuaMultiReturn<number[]>;
                                                               ~~~~~~~~~~~~~~

Error: Command failed: tstl -p tsconfig.json
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.compileMap (D:\Users\wc3-ts-template-master\scripts\utils.ts:108:3)
    at main (D:\Users\wc3-ts-template-master\scripts\test.ts:6:18)
    at Object.<anonymous> (D:\Users\wc3-ts-template-master\scripts\test.ts:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (D:\Users\wc3-ts-template-master\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Users\wc3-ts-template-master\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wc3-ts-template@1.0.0 test: `ts-node --transpile-only scripts/test.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wc3-ts-template@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```

I tried reinstalling Nodejs. Also tried clearing cache and reinstalling node-modules. 

OS: Windows 10

**Comment by TaBayram** [comment]
I had to add the line `"lua-types/core/index", `  to tsconfig.json manually in order to fix this issue.
